language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
branches:
  only:
    - development
services:
  - postgresql
addons:
  postgresql: "9.3"
cache:
  directories:
    - $HOME/.cache/pip
env:
  - NIGHTSHADES_POSTGRESQL_DB_STR='dbname=nightshades_test user=postgres'
install:
  - pip install -r requirements.test.txt
before_script:
  - psql -c 'CREATE DATABASE nightshades_test;' -U postgres
  - sh -c "find sql/*_migration.sql -exec psql -d nightshades_test -U postgres -f {} \;"
script:
  - coverage run tests.py
after_success:
  - coveralls
